### ISSUE TITLE
Missing empty cart trackings

### ISSUE THREAD

**Issue by tlescher** [emartech/magento1-extension#2]
https://github.com/emartech/magento1-extension/blob/eae43e669980c93bb176d09124a963120c3f46c1/app/code/community/Emartech/Emarsys/Block/Snipets.php#L86

> remove  "&& $cartData['items']"

https://dev.emarsys.com/v2/web-extend-command-reference/web-extend-cart
> "Issue this command on every page, even if the customer’s cart is empty."

**Comment by BlasiusVonSzerencsi** [comment]
Hi,

Thanks for opening the issue!

We have confirmed, that when you remove all cart items, the empty cart won't be pushed into the queue, thus sent to Emarsys.
We'll address the issue and notify you once the fix is available.

Thanks,
Balazs

**Comment by morzzz007** [comment]
Hi @tlescher 

This is fixed in the 1.2.5 release, thank you for pointing it out!
